<?php

use Helpyard\App\Controllers\StorefrontController;
use Helpyard\App\Controllers\AuthController;
use Helpyard\App\Controllers\CartController;
use Helpyard\App\Controllers\CheckoutController;
use Helpyard\App\Controllers\PaymentController;
use Helpyard\App\Controllers\AdminFulfillmentController;
use Helpyard\App\Controllers\DownloadController;
use Helpyard\App\Controllers\CourseController;
use Helpyard\App\Controllers\AdminFileController;
use Helpyard\App\Controllers\AdminCatalogController;
use Helpyard\App\Controllers\AdminCourseController;
use Helpyard\App\Controllers\AdminOrderController;
use Helpyard\App\Controllers\SeoController;
use Helpyard\App\Core\Router;

$auth = new AuthController($config['database']);
$cart = new CartController($config['database'], $config['payment']);
$checkout = new CheckoutController($config['database'], $config['payment']);
$payments = new PaymentController($config['database'], $config['payment']);
$adminFulfillment = new AdminFulfillmentController($config['database']);
$downloads = new DownloadController($config['database'], $config['app']['private_storage']);
$courses = new CourseController($config['database']);
$adminFiles = new AdminFileController($config['database'], $config['app']['private_storage']);
$adminCatalog = new AdminCatalogController($config['database']);
$adminCourses = new AdminCourseController($config['database']);
$adminOrders = new AdminOrderController($config['database']);
$seo = new SeoController($config['database'], $config['app']);
$webRouter = new Router();
$webRouter->get('/sitemap.xml', [$seo, 'sitemap']);
$webRouter->get('/robots.txt', [$seo, 'robots']);
$webRouter->get('/admin/courses', [$adminCourses, 'index']);
$webRouter->get('/admin/courses/lessons/{lesson_id}/edit', [$adminCourses, 'editLesson']);
$webRouter->post('/admin/courses', [$adminCourses, 'createCourse']);
$webRouter->post('/admin/courses/{course_id}/sections', [$adminCourses, 'createSection']);
$webRouter->post('/admin/courses/sections/{section_id}/lessons', [$adminCourses, 'createLesson']);
$webRouter->post('/admin/courses/lessons/{lesson_id}', [$adminCourses, 'updateLesson']);
$webRouter->get('/admin/orders', [$adminOrders, 'index']);
$webRouter->get('/admin/orders/{id}', [$adminOrders, 'show']);
$webRouter->post('/admin/orders/{id}/notes', [$adminOrders, 'addNote']);
$webRouter->get('/admin/catalog', [$adminCatalog, 'index']);
$webRouter->post('/admin/catalog/categories', [$adminCatalog, 'createCategory']);
$webRouter->post('/admin/catalog/categories/{id}', [$adminCatalog, 'updateCategory']);
$webRouter->post('/admin/catalog/products', [$adminCatalog, 'createProduct']);
$webRouter->post('/admin/catalog/products/{id}', [$adminCatalog, 'updateProduct']);
$webRouter->get('/admin/catalog/products/{id}/images', [$adminCatalog, 'productImages']);
$webRouter->post('/admin/catalog/products/{id}/images', [$adminCatalog, 'uploadProductImage']);
$webRouter->post('/admin/catalog/products/{product_id}/images/{image_id}/alt', [$adminCatalog, 'updateProductImageAlt']);
$webRouter->post('/admin/catalog/products/{product_id}/images/{image_id}/delete', [$adminCatalog, 'deleteProductImage']);
$webRouter->post('/admin/catalog/variants/{id}/stock', [$adminCatalog, 'updateVariantStock']);
$webRouter->get('/admin/files', [$adminFiles, 'index']);
$webRouter->post('/admin/files', [$adminFiles, 'upload']);
$webRouter->post('/admin/files/{id}/revoke', [$adminFiles, 'revoke']);
$webRouter->get('/account/courses', [$courses, 'index']);
$webRouter->get('/account/courses/{id}', [$courses, 'show']);
$webRouter->post('/account/courses/{id}/lessons/{lesson_id}/complete', [$courses, 'completeLesson']);
$webRouter->get('/account/downloads', [$downloads, 'index']);
$webRouter->get('/account/downloads/{id}', [$downloads, 'download']);
$webRouter->get('/admin/fulfillment', [$adminFulfillment, 'index']);
$webRouter->post('/admin/orders/{id}/fulfillment', [$adminFulfillment, 'advance']);
$webRouter->get('/cart', [$cart, 'show']);
$webRouter->post('/cart/items', [$cart, 'addItem']);
$webRouter->post('/cart/items/{id}/update', [$cart, 'updateItem']);
$webRouter->post('/cart/items/{id}/remove', [$cart, 'removeItem']);
$webRouter->get('/checkout', [$checkout, 'show']);
$webRouter->post('/checkout', [$checkout, 'createOrder']);
$webRouter->get('/orders/{id}', [$checkout, 'showOrder']);
$webRouter->post('/orders/{id}/pay', [$payments, 'initiate']);
$webRouter->post('/payments/ipn', [$payments, 'ipn']);
$webRouter->post('/payments/return/{result}', [$payments, 'browserReturn']);
$webRouter->get('/payments/return/{result}', [$payments, 'browserReturn']);
$webRouter->get('/register', [$auth, 'registerForm']);
$webRouter->post('/register', [$auth, 'register']);
$webRouter->get('/login', [$auth, 'loginForm']);
$webRouter->post('/login', [$auth, 'login']);
$webRouter->post('/logout', [$auth, 'logout']);
$webRouter->get('/account', [$auth, 'account']);
$webRouter->post('/account/profile', [$auth, 'updateProfile']);
$webRouter->get('/account/addresses', [$auth, 'addresses']);
$webRouter->post('/account/addresses', [$auth, 'addAddress']);
$webRouter->post('/account/addresses/{id}/delete', [$auth, 'deleteAddress']);
$storefront = new StorefrontController($config['database'], $config['app']);
$webRouter->get('/', [$storefront, 'index']);
$webRouter->get('/product/{slug}', [$storefront, 'product']);
$webRouter->get('/products', [$storefront, 'allProducts']);
$webRouter->get('/{section}', [$storefront, 'catalog']);

return $webRouter;
